export const survey_book = [
  {
    serial: '',
    title: 'INFORMATION REQUESTED WITHIN 1 HOUR',
    discriptions: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription: 'Roster/Sample Matrix (Changes may be made within 24 hours)',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Resident Census and Condition, CMS 672 (Changes may be made within 24 hours).',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'List of key facility personnel (DON, SSD, etc.).',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Staff person responsible for facility’s immunization program.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Residents who requested Medicare demand bills, by month for the last six months.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Facility building layout.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Policies and procedures to prevent and investigate allegations of abuse, neglect, and misappropriation of property and the name of the person to answer questions regarding these policies and investigations.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Copy of admission packet/contract(s) provided to all residents, including payment sources and resident rights information.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Meal times, dining locations, menus for survey week with serving sizes.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Medications pass times.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'List of all admissions during the past month and a list of all transfers/discharges for the past three months with their destinations.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'List of all residents receiving or have received antipsychotic medications over the past 30 days.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Application for Medicaid/Medicare (CMS 671).',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'List of residents age 55 and under.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Residents on hospice and dialysis.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '.',
    discription: 'Residents with discharge planned',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Residents who communicate with non-oral devices, sign language or do not speak English.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'INFORMATION REQUESTED WITHIN 24 HOURS',
    discriptions: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription: 'Current employees and SSN.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Hires since last survey with hire date and SSN.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Pain assessment, interventions and follow-up documentation are clearly evident?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Current activity schedule.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Annual Fire Department Consultation form.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Certification of Electrical Wiring.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Copy of Fire Alarm System Annual Inspection and current smoke detector sensitivity testing.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Sprinkler System Annual Inspection..',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Fire drill records for the past 12 months.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Resident evacuation plan.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Disaster plan for loss of water supply.',
    selected: false,
    comment: '',
    is_title: false,
  },
];

export const SURVEY_PREPAREDNESS = [
  {
    serial: '',
    title: '',
    discription:
      'Read your last annual survey and plan of correction. Sustain the plan!',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Make sure the last Annual Survey is posted.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Make sure “daily staffing” is posted, per federal requirements.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Make rounds daily using a variety of rounding tools or QA audit forms..',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Review QA Committee minutes, Grievance Log and Incidents for trends to focus on.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Review facility Quality Measure/Indicator Report for anything ranked above the 90th percentile.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Schedule Medication Pass Audits with consultant pharmacist.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Monitor dining service and room trays. Ask for a test tray and monitor hot food and cold food temperatures.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All meals served timely.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Interventions for residents with weight loss and gain? Are they care planned?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Make sure your staff is not handling food with bare hands.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Accurate and complete meal monitoring with an alternative menu posted and offered.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Conduct frequent Infection Control rounds with nursing assistants. Work toward making improvements.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Check refrigerator temps and temps for resident room refrigerators. Are they clean, food items labeled and dated?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Check microwaves. Are they clean?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are there unpleasant odors?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Conduct in-services, as needed. For example: one-on-one coaching at the bedside for proper pericare technique and pressure relief positioning.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'In-service staff for comprehension of residents’ rights, abuse, neglect, etc.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is your staff knocking on doors, waiting for permission to enter before entering a resident room?.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is your staff closing window curtains, privacy curtains, and room doors before providing care?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are privacy curtains missing, soiled?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Is fresh water within reach for each resident?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is there mold in shower rooms, cold and hot water temps, unsecured chemicals or sharps?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Is there linen, refuse, or devices on the floor?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are personal items labeled?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Oral care separate from pericare supplies?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Wheelchairs and seat cushions clean and free from odor?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Is your staff answering call lights within 3-5 minutes?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are call lights within reach?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are noise levels low - excessive overhead paging, staff chatter, unnecessary noise?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Do your employees know how to respond to complaints, concerns, or grievances?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are there background checks on all employees?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are licenses/certifications current?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are annual or new residents given a “two-step” TB skin check and are they up-to-date?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'CNAs compliant with 12-hours education annually?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Care plans address resident needs? Current and updated? Staff is following care according to care plans?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No holes in documentation? Check random MARs.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No missed signatures.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Staff performs proper hand washing between glove changes or between moving from soiled to clean?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Ensure proper wheelchair and bed positioning.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are glucometers being properly calibrated each month? Disinfected correctly? Used for more than one resident?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Check for good resident grooming i.e., post-meal grooming, good oral care, no facial hair (men and woman - unless residents choice and care planned), dirty nails, long finger and toe nails, etc.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Check designated smoking area. Proper cigarette disposal system in place? Smoking aprons? Supervision? No burn holes in clothing or linen.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Foley catheter tubing not on floor? Leg straps used? Bag covered?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Disaster/Emergency Preparedness. Does your staff know what to do?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Med carts clean?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Disposed of all expired meds?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Oxygen cylinders properly stored and chained?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'O2 tubing off floors?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No ice scoops stored in ice chests.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Labs are tracked and timely.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Dumpsters closed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: '24-hour report utilized.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Gait belts used. Fall prevention program in place.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Check restorative programs i.e. Walk-to-dine are functioning.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Fire drills done at varied times on different shifts.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are generators tested and run under load weekly?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is resident trust fund balanced and reconciled? Signed agreement in business file? Quarterly statements mailed and interest allocated to each account?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Activity calendar posted? Evening and weekend activities?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is resident mail delivered when received including Saturdays?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Are residents able and encouraged to vote during elections?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Safety committee in place and evidence that accidents/incidents are monitored.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is your Resident Census and Conditions (CMS 672) and your Application for Medicaid/Medicare (CMS 671) current?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Annual Fire Department Consultation form complete and current?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Certification of Electrical Wiring compete and current?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Do you have a written resident evacuation plan?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Do you have a disaster plan for loss of water supply?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are fire alarms inspected annually with recent smoke detector sensitivity test?',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are Sprinklers inspected annually? Quarterly flows test documentation? Weekly visual inspection documentation?',
    selected: false,
    comment: '',
    is_title: false,
  },
];

export const ADMINISTRATIVE_PREPAREDNESS = [
  {
    serial: '',
    title: '',
    discription: 'TB records and logs of residents and employees are to date.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Flu vaccines and Pneumovax are offered annually with proper consent obtained.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Sharps injury log is up to date.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Employee physicals are up to date, if applicable.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Hepatitis B declination and/or vaccinations are complete and documented in the employee’s personnel file.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Annual in-services on Infection Control and Standard Precautions and Safety have been held, are on file and have employee signatures indicating attendance.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Policies and procedures regarding Occupational Exposure are reviewed annually and updated to reflect new or modified tasks or procedures.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Exposure Control plan, Safety Manual and MSDS Sheets are accessible to employees.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Facility has an up to date disaster plan which is available to all departments.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Facility has a written protocol that defines the source of water for the facility to ensure water is available when there is a loss of normal water supply.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Employees have been instructed on proper lifting and handling techniques.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Employee files have documentation of infection control and safety orientation.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Handrails provided and are securely fastened.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Furniture and fixtures are free of splinters or sharp edges.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Desk and file drawers easily operated and anchored to prevent tipping.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All electric cords, plugs, switches are in good repair.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Smoking is allowed only in the designated areas, which are posted.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Storage areas are kept clean and orderly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All machines and heating elements are turned off at the end of office hours, or when not in use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All door alarms are checked weekly for functioning and logged.',
    selected: false,
    comment: '',
    is_title: false,
  },
];

export const KITCHEN_PREPAREDNESS = [
  {
    serial: '',
    title: '',
    discription: 'Milk, Eggs, Poultry, Fish, Meat stored and handled properly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Containers stored off of the floors.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Daily and weekly cleaning schedules are posted and followed. Temperature logs for freezers and coolers posted and documentation is complete.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All food is covered, labeled, and dated.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No personal items in coolers or freezers.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Dish Machines reach appropriate temp: Low Temp at 140 degrees or High Temp at 180 degrees with rinse.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Menus are followed with menu changes documented with RD signature.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Meal temps are recorded on the menu.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Meal looks appealing with appropriate garnish.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Exhaust hood clean with appropriate documentation.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Chemicals are stored away from food prep area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Hairnets are worn by all dietary employees and uniforms are clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Extended menus available.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Dumpster lid closed when not in use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Garbage pails are closed and stored away from food prep area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Ceiling is in good repair and appears clean with clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Unbroken light fixtures, all bulbs working and all bulbs covered.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Hood is free of grease, operational lights work, extinguisher nozzles free of grease and dust and the filters are clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Walk-in floors dry, fans clean, covered lighting.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Food transport prevents contamination.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Frozen foods are thawed properly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Slicer and mixer bowl are covered when unused.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All refuse containers are covered, clean and adequate.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'There is no sign of pest infestation.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Non-food and chemicals are stored away from food.',
    selected: false,
    comment: '',
    is_title: false,
  },
];

export const DEPARTMENT_PREPAREDNESS = [
  {
    serial: '',
    title: 'NURSING',
    discriptions: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription: 'Hand washing is followed per policy.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Isolation precautions are followed per policy.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Treatment cart is clean, stocked and well organized and disinfected as needed and locked when not in sight of nurse.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Top of cart is free of equipment, i.e. BP cuff, stethoscope.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Gloves and/or gowns are used appropriately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Hands are washed after removal of gloves.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Gloves are available and disposed of in resident’s room or plastic bag on dirty linen barrel.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Nurses dispose of contaminated dressings in biohazard containers.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Catheter care observed and completed correctly according to policy and procedure.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Tracheotomy care observed and completed according to policy and procedure.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Medication pass observed and completed correctly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Medication cart is clean and locked when not in sight of nurse.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Tube feeding procedure observed and completed correctly. Tube feeding equipment changed per protocol.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Oxygen tubing changed per protocol.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Policy and procedure for handling oxygen equipment is followed correctly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Cultures are obtained according to policy and procedure.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Work areas are kept free of food and drink.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled and stored in a closed, locked area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Nursing employees are in-serviced annually and understand and follow Standard Precautions / Infection Control and Safety Rules.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      ' Nursing employees can locate blood spill kit and verbalize correct usage of kit.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Items in bedside table drawer are separated and bagged.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Bedpans, urinals and washbasins present, clean and bagged if not stored in resident’s bedside table.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No perishable food is present in bedside tables.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Resident’s personal refrigerator clean and temp is = or < 40 degrees.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'No medication in bedside table (except for self-medicate with proper assessment and documentation).',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Wheelchairs clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Bedside commodes clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'IV poles clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Tube feeding pump and pole clean, bottles dated, tubing changed every 24 hours.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Nursing employees are in-serviced annually and understand and follow Standard Precautions / Infection Control, Safety Rules and Fire and Evacuation Plan.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Nursing staff understands and uses standard precautions appropriately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Nursing employees can locate blood spill kit and verbalize correct usage of kit.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Gloves, goggles and masks are used appropriately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Hallways are unobstructed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Exits are not locked or blocked.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Employees wear proper clothing and footwear.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Employees have been instructed on proper lifting and transferring techniques including mechanical and electrical lifts.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Gait belts are available and used.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'There is a method of identifying residents requiring 2 or 3 person transfer or mechanical lift.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Proper lifting equipment is utilized.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Combative residents are identified.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Proper footwear is worn.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All maintenance problems are reported for repair.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Electric cords for lights, radio, TV, etc. are safely placed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No electrical extension cards are in use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Bed adjustment handles are kept turned inward.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Chemicals are safely stored and handled.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Contaminated needles/sharps are disposed of in a puncture proof container.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All door alarms are checked for functioning and documented weekly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Proper instructions are given and applied when handling or using oxygen and other flammable gases.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      '“No Smoking” is enforced in rooms where oxygen is being administered.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Oxygen tanks are secured at all times.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Smoking is only allowed with proper supervision in designated areas.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Employees are trained in the use of fire extinguishers.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All wandering alarm bracelets are checked for placement and functioning daily and documented.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All door alarms are checked for functioning and documented weekly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'REHABILITATION',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription:
      'All equipment is cleaned and disinfected after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Service area is clean and free of peeling paint, chips, and cracked equipment',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Linens or towels are cleaned and stored in a cupboard when not in use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Sink is cleaned and disinfected after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled and stored in a closed, locked area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Proper hand washing is performed after each procedure.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Rehab employees are in-serviced annually and understand and follow Standard Precautions/Infection Control and Safety Rules.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Gloves, gowns and eye protection are used appropriately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Rehab employees can locate blood spill kit and verbalize correct usage of kit.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'HOUSEKEEPING',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription:
      'Floor is clean and free of debris and does not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Wall, ceilings and vents are clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Soap and paper towel dispensers are full.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Wastebaskets are lined with a plastic bag emptied daily and are non-combustible.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All doorknobs are disinfected daily.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All bathrooms are cleaned daily according to house- keeping’s policy.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Hallways and hallway handrails are cleaned and disinfected.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Mop water and mop heads are changed every 4 rooms or as needed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Regulated waste is handled per facility policy.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Garbage receptacles have covers and are cleaned and emptied daily in the dining room, utility rooms and medication rooms.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'The smoking area is clean and free of debris.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Ashtrays and ash cans are noncombustible and free of paper and plastic.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Carpets appear clean and spot free.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Utility gloves are worn and washed with soap and water',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Personal protective equipment such as gloves, goggles and gowns are used when handling potentially hazardous chemicals, acids, detergents',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Housekeeping employees are in-serviced annually and understand and follows Standard Precautions / Infection Control and Safety Rules.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Housekeeping carts are locked when not in sight.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Cleaning supplies are not easily accessible to cognitively impaired residents.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled, safely arranged and stored in a closed, locked area and staff is properly trained in their use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Housekeeping employees can locate blood spill kit and verbalize correct usage of kit.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Employees have been instructed on proper lifting and handling techniques.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Handles of tools are free of splinters and rough surfaces.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Buckets, tubs and pans are in good repair.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Vacuum cleaners, buffers and scrubbers are in good repair.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Electric tools are properly grounded.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Broken glass is properly and safely handled and disposed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Tools, carts and mop handles are placed to prevent interference with normal operations or tripping hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Spillages are wiped up immediately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: '“Wet Floor” caution signs are used when appropriate.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'A dry passage is maintained when mopping.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Equipment room is clean and orderly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Employees are trained in the use of fire extinguishers.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'LAUNDRY',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription: 'Clean linen is covered during transport.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All clean linen is kept separate from soiled linen.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All soiled linen is stored in a designated area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Contaminated linen (blood soaked) is adequately marked, kept separate from soiled linen and washed separately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Laundry appliances are cleaned according to Laundry’s Cleaning Policy.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Rubber gloves and water resistant gowns are worn during sorting of soiled laundry.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Washing machine wash temperature is maintained at degrees (may vary with concept program).',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Dryer temperature is maintained at 160 degrees (may vary with concept program).',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Lint is removed as needed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Soiled linen containers are lined with plastic bags.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Soiled lined barrels are cleaned per schedule.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Laundry employees are in-serviced annually and understand and follow Standard Precautions / Infection Control and Safety Rules and safe handling techniques of contaminated laundry.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled and stored in a closed, locked area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Laundry employees can locate blood spill kit and verbalize correct usage of kit.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Linen is NOT stained, torn or thread bare and there is a system in place to remove this type of linen.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Employees have been instructed on proper lifting and handling techniques.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Proper sorting and loading techniques are used, monitored and reinforced.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All V-belts, chain drives, gears or sprockets are guarded.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All electrical wiring is in conduit and safely fused with no evidence of corrosion.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Laundry carts are free of jagged edges.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All castered or wheeled equipment is in good repair.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Laundry floors are free of cracks and foreign matter and grates over floor drains..',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Pilot light areas on dryers are kept free of combustible build up.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Eye and hand protection is used when using acids, bleaches, soaps and detergent.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Chemical feed tubes are cleaned and maintained properly.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Laundry area has adequate ventilation.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Portable air fans safely arranged and guarded.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Fire emergency instructions are posted.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Laundry employees are trained in use of fire extinguishers.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Shower chairs are disinfected after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
];

export const ENVIRONMENT_PREPAREDNESS = [
  {
    serial: '',
    title: 'SHOWER / WHIRLPOOL ROOM',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription:
      'Tubs and whirlpool are disinfected and cleaned according to facility policy. Policy is posted in Shower room.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled and stored in a closed, locked area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Resident’s personal items are labeled.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Privacy curtains are in place and used.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Room is well ventilated.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Shower room is clean, odor free and no dust is present.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Sharps container readily available, capped when 3/4 full and NOT accessible to residents.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Shower floor is free of hazards and grates over floor drains.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Bathing facilities have non-slip surfaces.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Water temps are taken weekly and logged and within acceptable range. (NOT to exceed 110 degrees).',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'ACTIVITIES / SOCIAL SERVICES',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription:
      'All work areas are cleaned and disinfected after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All reusable equipment/supplies are cleaned and disinfected after resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Area is clean and free of peeling paint, chips, cracked furniture or equipment.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Activities/Social Services employees are in-serviced annually and understand and follow Standard Precautions/Infection Control.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Volunteers have been in-serviced on prevention and potential sources of infection.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled and stored in a closed, locked area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Activities/Social Services employees can locate blood spill kit and verbalize correct usage of kit.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Gloves and/or gowns are used appropriately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Activity employees are trained in use of fire extinguishers',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'BEAUTICIAN / BARBER',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription:
      'All work areas are cleaned and disinfected after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Service area is clean and free of peeling paint, chips, and cracked equipment.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All reusable equipment (brushes, combs, clips, curlers) are cleaned and disinfected after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Capes and towels are cleaned and stored in a cupboard when not in use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Sink is cleaned and disinfected after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Hair is removed from the floor after each resident’s haircut.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled and stored in a closed locked area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Proper hand washing is performed after each procedure.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Beautician and barber are in-serviced annually and understand and follow Standard Precautions/ Infection Control.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Beautician and barber can locate blood spill kit and verbalize correct usage of kit.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Gloves and/or gowns are used appropriately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'UTILITY ROOM',
    discription: '.',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription: 'Dirty utility hopper sink is clean and in working order.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Dirty linen barrels remain covered and emptied when necessary.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No linen barrels on floor at mealtime.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Barrels cleaned per facility schedule and policy.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Utility room clean and neat at end of each shift.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Dirty utility room is odor free.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Gloves, gowns and face protection available in the dirty utility room and used appropriately.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Disinfectant is stocked and available.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Chemicals are properly labeled and stored in a closed, locked area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Potential sources of infection are appropriately reported to Infection Control Officer / QA Committee.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'PHARMACY / MED ROOM / MEDICATION CART',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription: 'All work areas are cleaned and disinfected as needed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Sink is cleaned and disinfected.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floor is clean and free of debris.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Garbage receptacles have covers, are lined with a plastic bag and emptied daily or as needed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Medicine receptacles (i.e. souffl_ cups, plastic med cups) and water cups are stored in a clean and dry area.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Outside and inside of medication cart is clean.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Stock meds are stored in cabinets free from dust.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Med carts do not enter resident rooms.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Top of med cart is free of medication.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Oral and topical medications are separated in med cart.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Refrigerator clean and organized with a thermometer.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Refrigerator temps are taken and documented daily and are between 36 - 45 degrees.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Sharps containers are readily available, capped when 3/4 full and not accessible to residents.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors do not have any slip, trip or fall hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'CENTRAL SUPPLY',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription: 'All work areas are cleaned and disinfected as needed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Sink is cleaned and disinfected.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Floor is clean and free of debris.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Garbage receptacles have covers, are lined with plastic bag and emptied daily.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All reusable equipment is cleaned, disinfected and properly stored after each resident’s use.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All supplies are stored in an organized and neat manner.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Storage area is clean and free of peeling paint, chips, and cracked equipment.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Personal Protective Equipment (gloves, gowns, masks) is readily available and easy to locate.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Safety sharps devices (retractable syringes and lancets, and needleless IV supplies) are only used and are readily available and easy to locate.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No supplies are stored directly on the floor.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'HAZARDOUS WASTE',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription:
      'Sharps containers are readily available, capped when 3/4 full and are NOT accessible to residents.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Soiled utility rooms have biohazard signage.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Regulated waste containers are closable, leak proof, clearly marked and located in the soiled utility room.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Nurses dispose of contaminated dressings by double bagging.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Trash / garbage (non-contaminated) is not placed in the biohazard container.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Only safety sharps devices, such as retractable syringes and lancets, and needleless IV supplies are used.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Biohazard waste is picked up and disposed of by an outside source in a timely manner.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Disposal log is up to date and accurate.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS & Safety Manuals are available in each department.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: 'MAINTENANCE',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
  },
  {
    serial: '',
    title: '',
    discription:
      'Employees have been instructed on proper lifting and handling techniques.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Work areas are clean, orderly, and safely arranged.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Handrails are securely fixed to the wall and have no sharp edges or splinters.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All hand tools are in good repair, properly stored.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'No electrical appliances have frayed wires.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All electric and gasoline powered equipment are well maintained.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Point of operation guards are provided and used.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Eye protection is provided and used where required.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Elevated platforms, stepladders and extension ladders are well constructed and in good repair.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All ladders are provided with non-slip base.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Work areas are isolated or barricaded to prevent outside interference.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Electrical switch lockouts / tagouts are used when making repairs on machinery.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Warning signs or barricades are placed when work creates a hazard to others.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Loose tools and materials are located so tripping hazards are not created.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Safety lines are used when working above ground level.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All ropes, cables, chains, etc. are inspected and adequate for the job.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Safe methods are used when replacing burned out lights and tubes.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All electrical motors, machines, etc. on a preventive maintenance schedule.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'All electrical plugs, switches, cords in good repair',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'All wandering bracelets are checked daily for functioning and logged on MAR.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'No Proper type and number of fire extinguishers are available.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Employees are trained to use extinguisher.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Employees are instructed in fire reporting and emergency duties.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Departmental surveys are being reviewed and prompt action initiated on any safety hazards.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Annual Safety Objectives are on timetable for completion.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Workers’ Compensation claims are reviewed.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription: 'Resident incidents are reviewed in safety meetings.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Discipline procedures are being followed if employee violates safety rules.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'List of residents who require 2-3 person or Hoyer lift is posted on assignment sheet and care plan.',
    selected: false,
    comment: '',
    is_title: false,
  },
  {
    serial: '',
    title: '',
    discription:
      'Areas non-accessible to residents (mechanical rooms, oxygen storage, janitor’s closets, etc.) properly marked and locked to prevent sight impaired or confused residents from entering.',
    selected: false,
    comment: '',
    is_title: false,
  },
];
