export const NURSING = [
  {
    serial: '',
    title: '',
    discription:
      'The lab work for residents on Coumadin is completed as ordered and documentation of physician notification and assessment complete for abnormal INR/PT results?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 309,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are Blood Glucose levels obtained as ordered? Is assessment of resident with abnormal levels present?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 684,
  },
  {
    serial: '',
    title: '',
    discription:
      'Pain assessment, interventions and follow-up documentation are clearly evident?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 697,
  },
  {
    serial: '',
    title: '',
    discription:
      'Post falls assessment completed and appropriate? Interventions on plan of care are evident on physical review of resident? Care plan appropriate to falls?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are smoking safety assessments completed on all residents who smoke? When observing the resident that smoke is it evident that the safety interventions identified are in place?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription:
      'Timely assessment and physician notification is evident on any acute change of condition episodes.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [684, 580],
  },
  {
    serial: '',
    title: '',
    discription:
      'Do residents with pressure ulcers have had timely accurate assessment of wound with intervention and care plan in place?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 686,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are all incidents thoroughly investigated and documentation includes evidence of determining causal factors and recommendations to prevent reoccurrence?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 610,
  },
  {
    serial: '',
    title: '',
    discription: "Sharp containers aren't 3/4 full and properly disposal.",
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Meds are separated/stored appropriately.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'Med and treatment carts locked when unatteded.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'Biologicals and vials dated when opened.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'Glucose strips dated when opened.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'Narcotics double-locked.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'All meds current/check expiration dates.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'Employees food are not stored in refrigerator.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'All opened meds are stored separately from closed meds.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'Glucometer control logs are up to date.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 658,
  },
  {
    serial: '',
    title: '',
    discription: 'Respiratory and Treatment meds are stored appropriately.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'The E-Kit Policies & Procedures are being followed.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 658,
  },
  {
    serial: '',
    title: '',
    discription: 'The E-Kit contents are posted in nurses’ station.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 836,
  },
  {
    serial: '',
    title: '',
    discription: 'Are all expired meds removed and narcotic properly disposed?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 761,
  },
  {
    serial: '',
    title: '',
    discription: 'Are Quarterly Review Assessments completed and maintained?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 638,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are nurses, CNAs, or any staff member knocking and waiting for a response before entering resident’s room?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 550,
  },
  {
    serial: '',
    title: '',
    discription:
      'Nurse use hand sanitizer or wash hands before putting on gloves to administer medication or treatment? Wash or use hand sanitizer after removing gloves before exiting resident’s room?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [880, 550],
  },
  {
    serial: '',
    title: '',
    discription:
      'CNA close door, privacy curtains, and window blinds while providing personal care to resident? Resident completely covered during care?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 583,
  },
  {
    serial: '',
    title: '',
    discription:
      'CNA wash hands before wearing gloves to provide personal care to resident? CNA wash hands or using hand sanitizer after removing glove before exiting resident’s room?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription:
      'CNA remove gloves after changing resident’s brief and putting on new gloves to continue personal care to resident?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'CNA reposition residents every two hours and offer water?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [686, 692],
  },
  {
    serial: '',
    title: '',
    discription: 'Is resident’s mouth clean?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 684,
  },
  {
    serial: '',
    title: '',
    discription: 'Is resident’s nails trimmed and cleaned?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 684,
  },
  {
    serial: '',
    title: '',
    discription: 'Is hair combed and maintained?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 684,
  },
  {
    serial: '',
    title: '',
    discription: 'Are rooms free of signs?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 557,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are privacy curtains long enough to cover resident for privacy?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 557,
  },
  {
    serial: '',
    title: '',
    discription: 'Are siderails secure?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 700,
  },
  {
    serial: '',
    title: '',
    discription: 'Is Oxygen filters clean?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Is Oyxgen tubing dated?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 684,
  },
  {
    serial: '',
    title: '',
    discription: 'Are Oxygen signs posted?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 684,
  },
];

export const MDS = [
  {
    serial: '',
    title: '',
    discription:
      'Are MDS Data storage & maintenance for all resident assessments completed within the previous 15 months in the resident’s active record?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 639,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are comprehensive reviews complete of all ADL functional areas, cognitive status, and MDS categories triggering a RAP?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 636,
  },
  {
    serial: '',
    title: '',
    discription: 'MDS Dates Correct?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 638,
  },
  {
    serial: '',
    title: '',
    discription: 'Care Area Assessment, CAA, Summary Signed & Dated?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [641, 661, 636],
  },
  {
    serial: '',
    title: '',
    discription:
      'Care Area Assessment, CAA, completed for each triggered area?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [636, 641],
  },
  {
    serial: '',
    title: '',
    discription: 'Care Plan addresses each problem?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 656,
  },
  {
    serial: '',
    title: '',
    discription: 'Required signatures present?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 641,
  },
  {
    serial: '',
    title: '',
    discription: 'Location of Info Complete and Correct?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 639,
  },
  {
    serial: '',
    title: '',
    discription: 'Care Plan goals have timeframes and measureable?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 639,
  },
  {
    serial: '',
    title: '',
    discription:
      'Care Plan meetings schedule within 21 days of its completion?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [657, 553],
  },
  {
    serial: '',
    title: '',
    discription:
      'Change in Condition was documented? Were all appropriate parties notified in a timely manner?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 580,
  },
  {
    serial: '',
    title: '',
    discription: 'Are Annual Assessment update and completed?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 636,
  },
  {
    serial: '',
    title: '',
    discription: 'Mood/Behavior/Psychosocial are accurately assessed?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 641,
  },
  {
    serial: '',
    title: '',
    discription: "ADLs are accurately reflects resident's status?",
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 641,
  },
  {
    serial: '',
    title: '',
    discription:
      "Coding and Transmitting done within 7 days of completing resident's assessment?",
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 640,
  },
  {
    serial: '',
    title: '',
    discription:
      'Quarterly Review Assessments are scheduled, reviewed, and completed?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 638,
  },
  {
    serial: '',
    title: '',
    discription:
      'Preadmission Screening for MI was done on all residents admitted to the facility?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [644, 645],
  },
  {
    serial: '',
    title: '',
    discription: 'Post-Discharge Plan of Care was done on each resident?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [660, 661],
  },
  {
    serial: '',
    title: '',
    discription:
      'OBRA completed within 90 days from Assessment Reference Date, ADR (can be done early but not later)?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [641, 642],
  },
  {
    serial: '',
    title: '',
    discription: 'Death in the facility document within 7 days?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [641, 640],
  },
  {
    serial: '',
    title: '',
    discription:
      'Are Quarterly Assessment from each department submited and completed in a timely manner?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [638, 656],
  },
  {
    serial: '',
    title: '',
    discription:
      'Collaborating with each department for accuracy in therapy minutes, nursing restorative services, diet, activities, etc?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 640,
  },
];

export const THERAPY = [
  {
    serial: '',
    title: '',
    discription: 'Does residents receive timely screening (within 14 days)?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 636,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are resident’s assessments done timely, completed, and accurate?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [636, 635],
  },
  {
    serial: '',
    title: '',
    discription: 'Are physician’s orders clarified / accurate?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 635,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are Provision of Services for rehab services, such as but not limited to, PT, ST, OT or mental health rehab for mental illness or mental retardation in place.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 825,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are there written order by a physician for specialized rehabilitative services by qualified personnel?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 826,
  },
  {
    serial: '',
    title: '',
    discription: 'Are resident’s rehab services care planned?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 826,
  },
  {
    serial: '',
    title: '',
    discription: 'Is there Rehab dining areas that are designated and used.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 920,
  },
  {
    serial: '',
    title: '',
    discription: 'Are weekly progress notes completed?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 825,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is residents’ equipment in common areas sanitary, orderly, and in good repair? (Equipment in therapy rooms, bathing rooms, activity areas, etc.)',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [584, 810],
  },
  {
    serial: '',
    title: '',
    discription: 'Patient privacy during treatment?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 550,
  },
  {
    serial: '',
    title: '',
    discription: 'Oxygen storage appropriately?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'Are in-place Hydrocollator log temps; water color?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'No food in patient care areas.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Appropriate linen storag?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Chemicals stored appropriately.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'MSDS current (ultrasound gel).',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
];

export const DIETARY = [
  {
    serial: '',
    title: '',
    discription:
      'Are the refrigerator and freezer shelves and floors clean and free of spillage, and foods free of slime and mold?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is the freezer temperature 0 degrees F or below and refrigerator 41 degrees F or below (allow 2-3 degrees variance)? Do not check during meal preparation.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are refrigerated foods covered, dated, labeled, and shelved to allow air circulation?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are foods stored correctly (e.g., cooked foods over raw meat in refrigerator, egg and egg rich foods refrigerated)?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is dry storage maintained in a manner to prevent rodent/pest infestation?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are food contact surfaces and utensils cleaned to prevent cross-contamination and food-borne illness?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription: 'Are cooked foods cooled down safely?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are cracked eggs being used only in foods that are thoroughly cooked, such as baked goods or casseroles?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are frozen raw meats and poultry thawed in the refrigerator or in cold, running water?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are hot foods maintained at 140 degrees F or above and cold foods maintained at 41 degrees served from tray line?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are food trays, dinnerware, and utensils clean and in good condition?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are the foods covered until served? Is food protected from contamination during transportation and distribution?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are employees washing hands before and after handling food, using clean utensils when necessary and following infection control practices?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are food preparation equipment, dishes and utensils effectively sanitized to destroy potential food borne illness?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      "Is dishwasher's hot water wash 140 degrees F and rinse cycle 180 degrees F or chemical sanitation per manufacturer's instructions followed?",
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is facility following correct manual dishwashing procedures (i.e., 3 compartment sink, correct water temperature, chemical concentration, and immersion time)?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [812, 813],
  },
  {
    serial: '',
    title: '',
    discription: 'Are Quarterly Assessment completed in a timely manner?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [638, 639],
  },
  {
    serial: '',
    title: '',
    discription:
      'Are all containers in the refrigerator(s) labeled, dated and  labeled with a “use by” date and on the appropriate shelving.?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'Is the food in the refrigerator(s) in the original containers?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription: 'Is the floors under the stove and fryer clean?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription:
      'When was the last hood inspection? Is this in compliance with every 6 months?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 812,
  },
];

export const ENVIRON = [
  {
    serial: '',
    title: 'LAUNDRY',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription: 'Dryer and Ceiling filters are clean.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Doors closed between clean and soiled area.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription:
      'PPE available and used approperly. ( No gloves worn in the hallway)',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Shield/Goggles available for staff.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Gown (impervious gown or apron).',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Gloves available to staff.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Clean linen stain free and free from tears/holes.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 8584,
  },
  {
    serial: '',
    title: '',
    discription: "Chemicals secure in storage and on housekeeper's cart.",
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'Floors clean, waxed, no scratches, etc?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'Are all doors closed?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Wet floor signs available and properly used.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription:
      'No wax buildup in the corners of resident rooms and hallways.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [584, 921],
  },
  {
    serial: '',
    title: '',
    discription:
      'Resident’s room regularly deep cleaned with no dust build on window seal and furniture.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Air conditioner filters clean and free of dust buildup.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Ceiling fans free of dust buildup.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: 'MAINTNENANCE',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 812,
  },
  {
    serial: '',
    title: '',
    discription: 'Doors not propped open.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Fire extinguishers checked monthly.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription:
      'Fire alarm panel has tag within last year marked “functional”.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Exit signs visible and operational.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [907, 908],
  },
  {
    serial: '',
    title: '',
    discription: 'Biohazardous Waste locked with appropriate signage.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'Handrails firmly in all corridors.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 924,
  },
  {
    serial: '',
    title: '',
    discription: 'Appropriate door closures.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [908, 910],
  },
  {
    serial: '',
    title: '',
    discription: 'Water temperature 105-120 degrees.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Emergency outlets are colored red.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Corridors unobstructed.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 913,
  },
  {
    serial: '',
    title: '',
    discription: 'Storage off floors/18 “below ceiling.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'All Chemicals labeled and in MSDS Book.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'Chemicals stored properly/not left unattended.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'Equipment inspected regulary.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [584, 908],
  },
  {
    serial: '',
    title: '',
    discription: 'Ceiling filters clean.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 880,
  },
  {
    serial: '',
    title: '',
    discription: 'Liquid Oxygen (5 ft from electrical outlet)',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Tank storage properly.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Functional call lights.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 919,
  },
  {
    serial: '',
    title: '',
    discription: 'Air temperature (71-81 degrees F).',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 584,
  },
  {
    serial: '',
    title: '',
    discription:
      'Penetration of smoke barrier in place and meet Life Satey Codes Standards.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Shut-off valves labeled and legible.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 689,
  },
  {
    serial: '',
    title: '',
    discription: 'Exhaust fans working properly..',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription:
      'Designated smoking area for resident. (Does not apply to non-smoking facilities)',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 926,
  },
  {
    serial: '',
    title: '',
    discription: 'Extension cords 3-pronged',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 584,
  },
  {
    serial: '',
    title: '',
    discription: 'Call system functioning properly.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 919,
  },
  {
    serial: '',
    title: '',
    discription: 'Cords not frayed.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [908, 908],
  },
  {
    serial: '',
    title: '',
    discription: 'Garbage cans are fire rated.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 908,
  },
  {
    serial: '',
    title: '',
    discription: 'Safe storage of patient items.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 558,
  },
  {
    serial: '',
    title: '',
    discription: 'Safety Committee Meeting held regularly?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 868,
  },
];

export const SOCIAL = [
  {
    serial: '',
    title: 'RESIDENT AND ENVIRONMENT',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription: 'Physical condition of resident (comfort, positioning, etc.)?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 558,
  },
  {
    serial: '',
    title: '',
    discription: 'Appearance (grooming and attire)?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 550,
  },
  {
    serial: '',
    title: '',
    discription:
      'Physical environment (comfort, safety,privacy, infection control, stimulation, personal belongings, homelike)?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [583, 558],
  },
  {
    serial: '',
    title: '',
    discription:
      'Level of assistance received. Note instances of too much or too little and resulting problem (e.g., violation of dignity).',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [550, 684],
  },
  {
    serial: '',
    title: '',
    discription:
      'A “Notice of Medicare Non-Coverage” letter issued no later than 2 days before Part A and/or Part B covered services end.',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 836,
  },
  {
    serial: '',
    title: '',
    discription: 'Use of restraints and/or other restrictions on behavior?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 604,
  },
  {
    serial: '',
    title: '',
    discription:
      'Do staffs intervene to assist resident if there is a problem and the resident tries to indicate this?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 677,
  },
  {
    serial: '',
    title: 'DAILY LIFE',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'The agreement of the daily schedule and activities with assessed interests and functional level (Note during activities if cues/prompts and adapted equipment are provided as needed and according to care plan).',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'The agreement of the daily schedule and activities with assessed interests and functional level (Note during activities if cues/prompts and adapted equipment are provided as needed and according to care plan).',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'Restriction of choices that the resident can make (e.g., resident reaching out for a drink or pushing away food or medication and facility response).',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 578,
  },
  {
    serial: '',
    title: 'INTERACTIONS WITH OTHERS',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'Do staffs individualize their interactions with this resident, based on her/his preferences, capabilities, and special needs?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [550, 558],
  },
  {
    serial: '',
    title: '',
    discription:
      "What is the resident's response to staff nteractions? (smiling, attempting to communicate, distressed, anxious, etc.)",
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [550, 558],
  },
  {
    serial: '',
    title: '',
    discription:
      'Do staffs try to communicate in a reassuring way? (Note staff tone of voice and use of speech.)',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [550, 600],
  },
  {
    serial: '',
    title: '',
    discription:
      'While staff are giving care, do they include resident in conversation or do staff talk to each other as if resident is not there?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [550, 600],
  },
  {
    serial: '',
    title: '',
    discription:
      'Evidence of a roommate problem that could be ad- dressed by the facility?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 745,
  },
  {
    serial: '',
    title: '',
    discription:
      'Consistency of opportunities for socializing with regard to assessed interests and functional level. (Note time and situations when isolated.)',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: true,
    btn: [571, 561],
  },
  {
    serial: '',
    title: '',
    discription:
      'Location of resident: segregated in some way, in a special unit, or fully integrated with other residents. (Note any adverse consequences for resident.)',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 603,
  },
  {
    serial: '',
    title: '',
    discription:
      'Grievance procedure in place for residents and family members?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 585,
  },
];

export const ACTIVITIES = [
  {
    serial: '',
    title: 'DECISIONS',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are residents involved in making choices about your daily activities?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription: 'Are there activities available on the weekends?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 679,
  },
  {
    serial: '',
    title: '',
    discription: 'Are all activities visually posted for all residents to see?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'Do residents participate in meetings where staff plan their activities and daily medical and nursing care?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 657,
  },
  {
    serial: '',
    title: '',
    discription: 'Are religious/spiritual activities offered?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: 'ACTIVITIES',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are various types of social and recreational activities offered?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 679,
  },
  {
    serial: '',
    title: '',
    discription: 'Are residents satisfied with schedule activities?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are there enough help and supplies available so that everyone who wants to can participate?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 679,
  },
  {
    serial: '',
    title: '',
    discription:
      'Outside of the formal activity programs, are there opportunities for you to socialize with other residents?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 679,
  },
  {
    serial: '',
    title: 'COUNCIL MEETING',
    discription: '',
    selected: false,
    comment: '',
    is_title: true,
    is_btn_mutipal: false,
    btn: 561,
  },
  {
    serial: '',
    title: '',
    discription:
      'Does the resident council committee communicate its concerns to the facility?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 565,
  },
  {
    serial: '',
    title: '',
    discription:
      'Does the facility help you with arrangements for council meetings?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 565,
  },
  {
    serial: '',
    title: '',
    discription: "Does the administrator respond to the council's concerns?",
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 565,
  },
  {
    serial: '',
    title: '',
    discription: 'Does the facility make sure residents have space to meet?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 565,
  },
  {
    serial: '',
    title: '',
    discription:
      'Are resident able to have meetings without any staff present if you wish?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 565,
  },
  {
    serial: '',
    title: '',
    discription:
      'When the facility cannot accommodate a council request, do they give you a reasonable explanation?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 565,
  },
  {
    serial: '',
    title: '',
    discription:
      'If the resident is in the room, consistency of TV or radion being on with assessed interest?',
    selected: false,
    comment: '',
    is_title: false,
    is_btn_mutipal: false,
    btn: 561,
  },
];
